module.exports = {
    addApp: "add_app",
    awaConfirm: "aw_confirm",
    activeApp: "act_app",
    inUse: "in_use",
    hideApp: "hide_app",
    banApp: "ban_app",
    statistic: "stats",
    home: "return_home",
    back: "return_back",
    cancelPay: "cancel_pay",
    contactUser: "contact_user",
    hidesApp: "hides_app",
    shareApp: "share_app",
    deleteApp: "delete_app",
    changeReff: "change_ref",
    changeRedirectP: "change_redirect_p",
    changeGeoApp: "change_geo_app",
    shareAppToUser: "share_app_to_user",
    shareYes: "share_yes",
    shareNo: "share_no",
    showApp: "show_app",
    penndingApp: "pendding_app",
    setImageUrl: "set_img_url",
    setActiveApp: "set_active_app",
    changePrice: "change_price",
    chekGooglePlay: "chekGooglePlay",
    hidedApps: "hided_apps",
    makeActive: "make_active",
    cleanUrl: "clean_url",
    setNaming: "set_naming",
    switchLink: "switch_link",
    sendToModerate: "send_to_moderate",
    sendToBan: "send_to_ban",
    setPriceAndBaner: "set_price_and_baner",
    changeDateRedirect: "change_date_redirect",
    deleteRedirect: "delete_redirect"


}